var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},e),ba=[],ca="./this.program",h=(a,b)=>{throw b;},da="object"==typeof window,k="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,u,v;
if(ea){var fs=require("fs"),ha=require("path");q=k?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};u=(a,b,c)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);process.on("uncaughtException",
function(a){if(!(a instanceof w))throw a;});if(15>process.version.match(/^v(\d+)\./)[1])process.on("unhandledRejection",function(a){throw a;});h=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof w||x("exiting due to exception: "+b);process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(da||k)k?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+
1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},k&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};e.print||console.log.bind(console);var x=e.printErr||console.warn.bind(console);
Object.assign(e,aa);aa=null;e.arguments&&(ba=e.arguments);e.thisProgram&&(ca=e.thisProgram);e.quit&&(h=e.quit);var y;e.wasmBinary&&(y=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!=typeof WebAssembly&&z("no native wasm support detected");var ia,ja=!1,ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function A(a,b){if(a){var c=B,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&ka)a=ka.decode(c.subarray(a,b));else{for(d="";a<b;){var f=c[a++];if(f&128){var l=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|l);else{var g=c[a++]&63;f=224==(f&240)?(f&15)<<12|l<<6|g:(f&7)<<18|l<<12|g<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}
function C(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var l=0;l<a.length;++l){var g=a.charCodeAt(l);if(55296<=g&&57343>=g){var m=a.charCodeAt(++l);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function la(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var ma,B,na,oa,D,pa,qa,E,F,ra=[],sa=[],ta=[],ua=[],va=[];function wa(){var a=e.preRun.shift();ra.unshift(a)}var G=0,xa=null,H=null;function z(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";x(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function ya(){return I.startsWith("data:application/octet-stream;base64,")}var I;
I="pacman.wasm";if(!ya()){var za=I;I=e.locateFile?e.locateFile(za,q):q+za}function Aa(){var a=I;try{if(a==I&&y)return new Uint8Array(y);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ba(){if(!y&&(da||k)){if("function"==typeof fetch&&!I.startsWith("file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Aa()});if(u)return new Promise(function(a,b){u(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Aa()})}function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function K(a){for(;0<a.length;)a.shift()(e)}function Ca(a){var b=Da();a();Ea(b)}var Fa=0;function Ga(){for(var a=L.length-1;0<=a;--a)Ha(a);L=[];M=[]}var M=[];function Ia(){if(Fa&&Ja.Lb)for(var a=0;a<M.length;++a){var b=M[a];M.splice(a,1);--a;b.uc.apply(null,b.kc)}}var L=[];function Ha(a){var b=L[a];b.target.removeEventListener(b.Db,b.ec,b.Eb);L.splice(a,1)}
function N(a){function b(d){++Fa;Ja=a;Ia();a.Gb(d);Ia();--Fa}if(a.Fb)a.ec=b,a.target.addEventListener(a.Db,b,a.Eb),L.push(a),Ka||(ua.push(Ga),Ka=!0);else for(var c=0;c<L.length;++c)L[c].target==a.target&&L[c].Db==a.Db&&Ha(c--)}function La(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Ka,Ja,Ma,Na,O,Oa,Pa,Qa,Ra,Sa=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function Q(a){a=2<a?A(a):a;return Sa[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Ta(a){return 0>Sa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Ua(a,b,c,d,f,l){Ma||(Ma=R(256));a={target:Q(a),Db:l,Fb:d,Gb:function(g=event){var m=g.target.id?g.target.id:"",n=Ma;C(La(g.target),B,n+0,128);C(m,B,n+128,128);F.get(d)(f,n,b)&&g.preventDefault()},Eb:c};N(a)}
function Va(a,b,c,d,f,l){Na||(Na=R(176));a={target:Q(a),Lb:!0,Db:l,Fb:d,Gb:function(g){var m=Na;E[m>>3]=g.timeStamp;var n=m>>2;D[n+2]=g.location;D[n+3]=g.ctrlKey;D[n+4]=g.shiftKey;D[n+5]=g.altKey;D[n+6]=g.metaKey;D[n+7]=g.repeat;D[n+8]=g.charCode;D[n+9]=g.keyCode;D[n+10]=g.which;C(g.key||"",B,m+44,32);C(g.code||"",B,m+76,32);C(g.char||"",B,m+108,32);C(g.locale||"",B,m+140,32);F.get(d)(f,m,b)&&g.preventDefault()},Eb:c};N(a)}
function Wa(a,b,c){E[a>>3]=b.timeStamp;a>>=2;D[a+2]=b.screenX;D[a+3]=b.screenY;D[a+4]=b.clientX;D[a+5]=b.clientY;D[a+6]=b.ctrlKey;D[a+7]=b.shiftKey;D[a+8]=b.altKey;D[a+9]=b.metaKey;na[2*a+20]=b.button;na[2*a+21]=b.buttons;D[a+11]=b.movementX;D[a+12]=b.movementY;c=Ta(c);D[a+13]=b.clientX-c.left;D[a+14]=b.clientY-c.top}
function S(a,b,c,d,f,l){O||(O=R(72));a=Q(a);N({target:a,Lb:"mousemove"!=l&&"mouseenter"!=l&&"mouseleave"!=l,Db:l,Fb:d,Gb:function(g=event){Wa(O,g,a);F.get(d)(f,O,b)&&g.preventDefault()},Eb:c})}function T(a,b,c,d,f){Oa||(Oa=R(260));N({target:a,Db:f,Fb:d,Gb:function(l=event){var g=Oa,m=document.pointerLockElement||document.Ib||document.Sb||document.Rb;D[g>>2]=!!m;var n=m&&m.id?m.id:"";C(La(m),B,g+4,128);C(n,B,g+132,128);F.get(d)(20,g,b)&&l.preventDefault()},Eb:c})}
function Xa(a,b,c,d,f){N({target:a,Db:f,Fb:d,Gb:function(l=event){F.get(d)(38,0,b)&&l.preventDefault()},Eb:c})}
function Ya(a,b,c,d){Pa||(Pa=R(36));a=Q(a);N({target:a,Db:"resize",Fb:d,Gb:function(f=event){if(f.target==a){var l=document.body;if(l){var g=Pa;D[g>>2]=f.detail;D[g+4>>2]=l.clientWidth;D[g+8>>2]=l.clientHeight;D[g+12>>2]=innerWidth;D[g+16>>2]=innerHeight;D[g+20>>2]=outerWidth;D[g+24>>2]=outerHeight;D[g+28>>2]=pageXOffset;D[g+32>>2]=pageYOffset;F.get(d)(10,g,b)&&f.preventDefault()}}},Eb:c})}
function Za(a,b,c,d,f,l){Qa||(Qa=R(1696));a=Q(a);N({target:a,Lb:"touchstart"==l||"touchend"==l,Db:l,Fb:d,Gb:function(g){for(var m,n={},r=g.touches,t=0;t<r.length;++t)m=r[t],m.Ub=m.Vb=0,n[m.identifier]=m;for(t=0;t<g.changedTouches.length;++t)m=g.changedTouches[t],m.Ub=1,n[m.identifier]=m;for(t=0;t<g.targetTouches.length;++t)n[g.targetTouches[t].identifier].Vb=1;r=Qa;E[r>>3]=g.timeStamp;var p=r>>2;D[p+3]=g.ctrlKey;D[p+4]=g.shiftKey;D[p+5]=g.altKey;D[p+6]=g.metaKey;p+=7;var J=Ta(a),P=0;for(t in n)if(m=
n[t],D[p]=m.identifier,D[p+1]=m.screenX,D[p+2]=m.screenY,D[p+3]=m.clientX,D[p+4]=m.clientY,D[p+5]=m.pageX,D[p+6]=m.pageY,D[p+7]=m.Ub,D[p+8]=m.Vb,D[p+9]=m.clientX-J.left,D[p+10]=m.clientY-J.top,p+=13,31<++P)break;D[r+8>>2]=P;F.get(d)(f,r,b)&&g.preventDefault()},Eb:c})}function $a(a,b,c,d,f,l){a={target:Q(a),Db:l,Fb:d,Gb:function(g=event){F.get(d)(f,0,b)&&g.preventDefault()},Eb:c};N(a)}
function ab(a,b,c,d){Ra||(Ra=R(104));N({target:a,Lb:!0,Db:"wheel",Fb:d,Gb:function(f=event){var l=Ra;Wa(l,f,a);E[l+72>>3]=f.deltaX;E[l+80>>3]=f.deltaY;E[l+88>>3]=f.deltaZ;D[l+96>>2]=f.deltaMode;F.get(d)(9,l,b)&&f.preventDefault()},Eb:c})}
function bb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,l){b.drawArraysInstancedANGLE(c,d,f,l)},a.drawElementsInstanced=function(c,d,f,l,g){b.drawElementsInstancedANGLE(c,d,f,l,g)})}
function cb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function db(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function eb(a){a.pc=a.getExtension("WEBGL_multi_draw")}
var fb=1,gb=[],U=[],hb=[],V=[],W=[],X=[],ib=[],jb={},kb=4;function Y(a){lb||(lb=a)}function mb(a){for(var b=fb++,c=a.length;c<b;c++)a[c]=null;return b}function nb(a,b){a.Ib||(a.Ib=a.getContext,a.getContext=function(d,f){f=a.Ib(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?ob(c,b):0}function ob(a,b){var c=mb(ib),d={nc:c,attributes:b,version:b.ic,Pb:a};a.canvas&&(a.canvas.jc=d);ib[c]=d;("undefined"==typeof b.Tb||b.Tb)&&pb(d);return c}
function pb(a){a||(a=qb);if(!a.hc){a.hc=!0;var b=a.Pb;bb(b);cb(b);db(b);b.mc=b.getExtension("EXT_disjoint_timer_query");eb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var lb,qb,rb=["default","low-power","high-performance"];function sb(a,b,c,d){for(var f=0;f<a;f++){var l=Z[c](),g=l&&mb(d);l?(l.name=g,d[g]=l):Y(1282);D[b+4*f>>2]=g}}
function tb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)D[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Y(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Y(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}D[b>>2]=c}else Y(1281)}function ub(a){var b=la(a)+1,c=R(b);C(a,B,c,b);return c}
function vb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function wb(a){if(!noExitRuntime){if(e.onExit)e.onExit(a);ja=!0}h(a,new w(a))}function xb(a){var b=la(a)+1,c=yb(b);C(a,ma,c,b);return c}
var Z,Gb={h:function(){z("")},N:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},fa:function(a,b,c){a=Q(a);if(!a)return-4;a=Ta(a);E[b>>3]=a.width;E[c>>3]=a.height;return 0},Za:function(a,b,c){B.copyWithin(a,b,b+c)},Ta:function(a,b){function c(d){F.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ya:function(){z("OOM")},P:function(a,b,c,d){Ua(a,b,c,d,12,"blur");return 0},L:function(a,b,c){a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},Q:function(a,
b,c,d){Ua(a,b,c,d,13,"focus");return 0},Z:function(a,b,c,d){Va(a,b,c,d,2,"keydown");return 0},X:function(a,b,c,d){Va(a,b,c,d,1,"keypress");return 0},Y:function(a,b,c,d){Va(a,b,c,d,3,"keyup");return 0},t:function(a,b,c,d){S(a,b,c,d,5,"mousedown");return 0},aa:function(a,b,c,d){S(a,b,c,d,33,"mouseenter");return 0},$:function(a,b,c,d){S(a,b,c,d,34,"mouseleave");return 0},da:function(a,b,c,d){S(a,b,c,d,8,"mousemove");return 0},ea:function(a,b,c,d){S(a,b,c,d,6,"mouseup");return 0},S:function(a,b,c,d){if(!document||
!document.body||!(document.body.requestPointerLock||document.body.Ib||document.body.Sb||document.body.Rb))return-1;a=Q(a);if(!a)return-4;T(a,b,c,d,"pointerlockchange");T(a,b,c,d,"mozpointerlockchange");T(a,b,c,d,"webkitpointerlockchange");T(a,b,c,d,"mspointerlockchange");return 0},R:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Ib||document.body.Sb||document.body.Rb))return-1;a=Q(a);if(!a)return-4;Xa(a,b,c,d,"pointerlockerror");Xa(a,b,c,d,"mozpointerlockerror");
Xa(a,b,c,d,"webkitpointerlockerror");Xa(a,b,c,d,"mspointerlockerror");return 0},Xa:function(a,b,c,d){Ya(a,b,c,d);return 0},T:function(a,b,c,d){Za(a,b,c,d,25,"touchcancel");return 0},U:function(a,b,c,d){Za(a,b,c,d,23,"touchend");return 0},V:function(a,b,c,d){Za(a,b,c,d,24,"touchmove");return 0},W:function(a,b,c,d){Za(a,b,c,d,22,"touchstart");return 0},O:function(a,b,c,d){$a(a,b,c,d,31,"webglcontextlost");return 0},M:function(a,b,c,d){$a(a,b,c,d,32,"webglcontextrestored");return 0},_:function(a,b,c,
d){a=Q(a);return"undefined"!=typeof a.onwheel?(ab(a,b,c,d),0):-1},F:function(a,b){b>>=2;b={alpha:!!D[b],depth:!!D[b+1],stencil:!!D[b+2],antialias:!!D[b+3],premultipliedAlpha:!!D[b+4],preserveDrawingBuffer:!!D[b+5],powerPreference:rb[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+7],ic:D[b+8],oc:D[b+9],Tb:D[b+10],fc:D[b+11],qc:D[b+12],rc:D[b+13]};a=Q(a);return!a||b.fc?0:nb(a,b)},sa:function(a,b){a=ib[a];b=A(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&bb(Z);"OES_vertex_array_object"==
b&&cb(Z);"WEBGL_draw_buffers"==b&&db(Z);"WEBGL_multi_draw"==b&&eb(Z);return!!a.Pb.getExtension(b)},Ha:function(a){a>>=2;for(var b=0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=D[a+8]=D[a+10]=1},ya:function(a){qb=ib[a];e.lc=Z=qb&&qb.Pb;return!a||Z?0:-5},q:function(a){Z.activeTexture(a)},I:function(a,b){Z.attachShader(U[a],X[b])},b:function(a,b){Z.bindBuffer(a,gb[b])},f:function(a,b){Z.bindFramebuffer(a,hb[b])},Ka:function(a,b){Z.bindRenderbuffer(a,V[b])},g:function(a,b){Z.bindTexture(a,W[b])},x:function(a,
b,c,d){Z.blendColor(a,b,c,d)},y:function(a,b){Z.blendEquationSeparate(a,b)},z:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},Ma:function(a,b,c,d){Z.bufferData(a,c?B.subarray(c,c+b):b,d)},J:function(a,b,c,d){Z.bufferSubData(a,b,B.subarray(d,d+c))},C:function(a){return Z.checkFramebufferStatus(a)},ua:function(a){Z.clear(a)},xa:function(a,b,c,d){Z.clearColor(a,b,c,d)},wa:function(a){Z.clearDepth(a)},va:function(a){Z.clearStencil(a)},i:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},$a:function(a){Z.compileShader(X[a])},
Ga:function(a,b,c,d,f,l,g,m){Z.compressedTexImage2D(a,b,c,d,f,l,m?B.subarray(m,m+g):null)},Ea:function(){var a=mb(U),b=Z.createProgram();b.name=a;b.Ob=b.Mb=b.Nb=0;b.Qb=1;U[a]=b;return a},bb:function(a){var b=mb(X);X[b]=Z.createShader(a);return b},w:function(a){Z.cullFace(a)},Oa:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],f=gb[d];f&&(Z.deleteBuffer(f),f.name=0,gb[d]=null)}},p:function(a,b){for(var c=0;c<a;++c){var d=D[b+4*c>>2],f=hb[d];f&&(Z.deleteFramebuffer(f),f.name=0,hb[d]=null)}},K:function(a){if(a){var b=
U[a];b?(Z.deleteProgram(b),b.name=0,U[a]=null):Y(1281)}},ca:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],f=V[d];f&&(Z.deleteRenderbuffer(f),f.name=0,V[d]=null)}},o:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},eb:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],f=W[d];f&&(Z.deleteTexture(f),f.name=0,W[d]=null)}},l:function(a){Z.depthFunc(a)},m:function(a){Z.depthMask(!!a)},a:function(a){Z.disable(a)},u:function(a){Z.disableVertexAttribArray(a)},ka:function(a,b,
c){Z.drawArrays(a,b,c)},la:function(a,b,c,d){Z.drawArraysInstanced(a,b,c,d)},ma:function(a,b,c,d){Z.drawElements(a,b,c,d)},na:function(a,b,c,d,f){Z.drawElementsInstanced(a,b,c,d,f)},d:function(a){Z.enable(a)},oa:function(a){Z.enableVertexAttribArray(a)},n:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,V[d])},D:function(a,b,c,d,f){Z.framebufferTexture2D(a,b,c,W[d],f)},v:function(a){Z.frontFace(a)},Na:function(a,b){sb(a,b,"createBuffer",gb)},E:function(a,b){sb(a,b,"createFramebuffer",hb)},La:function(a,
b){sb(a,b,"createRenderbuffer",V)},Ia:function(a,b){sb(a,b,"createTexture",W)},Aa:function(a,b){return Z.getAttribLocation(U[a],A(b))},c:function(a,b){tb(a,b)},Ca:function(a,b,c,d){a=Z.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,B,d,b):0;c&&(D[c>>2]=b)},H:function(a,b,c){if(c)if(a>=fb)Y(1281);else if(a=U[a],35716==b)a=Z.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.Ob)for(b=0;b<Z.getProgramParameter(a,35718);++b)a.Ob=Math.max(a.Ob,
Z.getActiveUniform(a,b).name.length+1);D[c>>2]=a.Ob}else if(35722==b){if(!a.Mb)for(b=0;b<Z.getProgramParameter(a,35721);++b)a.Mb=Math.max(a.Mb,Z.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.Mb}else if(35381==b){if(!a.Nb)for(b=0;b<Z.getProgramParameter(a,35382);++b)a.Nb=Math.max(a.Nb,Z.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.Nb}else D[c>>2]=Z.getProgramParameter(a,b);else Y(1281)},_a:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,B,d,b):0;c&&(D[c>>
2]=b)},ba:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),D[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(X[a]),D[c>>2]=a?a.length+1:0):D[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},Qa:function(a){var b=jb[a];if(!b){switch(a){case 7939:b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ub(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||Y(1280);b=b&&ub(b);break;case 7938:b=ub("OpenGL ES 2.0 ("+
Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ub(b);break;default:Y(1280)}jb[a]=b}return b},G:function(a,b){b=A(b);if(a=U[a]){var c=a,d=c.Kb,f=c.cc,l;if(!d)for(c.Kb=d={},c.bc={},l=0;l<Z.getProgramParameter(c,35718);++l){var g=Z.getActiveUniform(c,l);var m=g.name;g=g.size;var n=vb(m);n=0<n?m.slice(0,n):m;var r=c.Qb;c.Qb+=g;f[n]=[g,r];for(m=
0;m<g;++m)d[r]=m,c.bc[r++]=n}c=a.Kb;d=0;f=b;l=vb(b);0<l&&(d=parseInt(b.slice(l+1))>>>0,f=b.slice(0,l));if((f=a.cc[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||Z.getUniformLocation(a,b)))return d}else Y(1281);return-1},Da:function(a){a=U[a];Z.linkProgram(a);a.Kb=0;a.cc={}},Pa:function(a,b){3317==a&&(kb=b);Z.pixelStorei(a,b)},A:function(a,b){Z.polygonOffset(a,b)},Ja:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},za:function(a,b,c,d){Z.scissor(a,b,c,d)},ab:function(a,b,c,d){for(var f="",l=0;l<b;++l){var g=d?
D[d+4*l>>2]:-1;f+=A(D[c+4*l>>2],0>g?void 0:g)}Z.shaderSource(X[a],f)},db:function(a,b,c){Z.stencilFunc(a,b,c)},ta:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},k:function(a){Z.stencilMask(a)},cb:function(a,b,c){Z.stencilOp(a,b,c)},ra:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},Fa:function(a,b,c,d,f,l,g,m,n){var r=Z,t=r.texImage2D;if(n){var p=m-5120;p=1==p?B:4==p?D:6==p?qa:5==p||28922==p?pa:oa;var J=31-Math.clz32(p.BYTES_PER_ELEMENT),P=kb;n=p.subarray(n>>J,n+f*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-
6402]||1)*(1<<J)+P-1&-P)>>J)}else n=null;t.call(r,a,b,c,d,f,l,g,m,n)},e:function(a,b,c){Z.texParameteri(a,b,c)},Ba:function(a,b){var c=Z,d=c.uniform1i;var f=Z.dc;if(f){var l=f.Kb[a];"number"==typeof l&&(f.Kb[a]=l=Z.getUniformLocation(f,f.bc[a]+(0<l?"["+l+"]":"")));a=l}else Y(1282),a=void 0;d.call(c,a,b)},j:function(a){a=U[a];Z.useProgram(a);Z.dc=a},pa:function(a,b){Z.vertexAttribDivisor(a,b)},qa:function(a,b,c,d,f,l){Z.vertexAttribPointer(a,b,c,!!d,f,l)},B:function(a,b,c,d){Z.viewport(a,b,c,d)},Wa:function(){e.Wb=
a=>{0!=zb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.Wb)},Va:function(){e.ac=a=>{const b=a.clipboardData.getData("text");Ca(()=>{const c=xb(b);Ab(c)})};window.addEventListener("paste",e.ac)},Ua:function(a){e.sc=[];a=A(a);a=document.getElementById(a);e.Xb=b=>{b.stopPropagation();b.preventDefault()};e.Yb=b=>{b.stopPropagation();b.preventDefault()};e.Zb=b=>{b.stopPropagation();b.preventDefault()};e.$b=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;
e.tc=c;Bb(c.length);for(let d=0;d<c.length;d++)Ca(()=>{const f=xb(c[d].name);Cb(d,f)});Db(b.clientX,b.clientY)};a.addEventListener("dragenter",e.Xb,!1);a.addEventListener("dragleave",e.Yb,!1);a.addEventListener("dragover",e.Zb,!1);a.addEventListener("drop",e.$b,!1)},Sa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},hb:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",
function(){Eb()});document.body.append(a)},gb:function(){document.getElementById("_sokol_app_input_element").focus()},lb:function(a){a=A(a);e.Jb=document.getElementById(a);e.Jb||console.log("sokol_app.h: invalid target:"+a);e.Jb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},kb:function(){window.removeEventListener("beforeunload",e.Wb)},jb:function(){window.removeEventListener("paste",e.ac)},ib:function(a){a=A(a);a=document.getElementById(a);a.removeEventListener("dragenter",
e.Xb);a.removeEventListener("dragleave",e.Yb);a.removeEventListener("dragover",e.Zb);a.removeEventListener("drop",e.$b)},r:function(){e.Jb&&e.Jb.requestPointerLock&&e.Jb.requestPointerLock()},Ra:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const f=d.getContext("2d"),l=f.createImageData(a,b);l.data.set(B.subarray(c,c+a*b*4));f.putImageData(l,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},
fb:function(){document.getElementById("_sokol_app_input_element").blur()},ha:function(){return e.Hb?e.Hb.bufferSize:0},ja:function(a,b,c){e.Cb=null;e.Hb=null;"undefined"!==typeof AudioContext?e.Cb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Cb=null,console.log("sokol_audio.h: no WebAudio support"));return e.Cb?(console.log("sokol_audio.h: sample rate ",e.Cb.sampleRate),e.Hb=e.Cb.createScriptProcessor(c,0,b),e.Hb.onaudioprocess=d=>{const f=d.outputBuffer.length,l=Fb(f);if(l){const g=
d.outputBuffer.numberOfChannels;for(let m=0;m<g;m++){const n=d.outputBuffer.getChannelData(m);for(let r=0;r<f;r++)n[r]=qa[(l>>2)+(g*r+m)]}}},e.Hb.connect(e.Cb.destination),a=()=>{e.Cb&&"suspended"===e.Cb.state&&e.Cb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ia:function(){return e.Cb?e.Cb.sampleRate:0},ga:function(){const a=e.Cb;null!==a&&(e.Hb&&e.Hb.disconnect(),a.close(),e.Cb=null,
e.Hb=null)},s:function(a,b){b=A(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
(function(){function a(f){e.asm=f.exports;ia=e.asm.mb;f=ia.buffer;e.HEAP8=ma=new Int8Array(f);e.HEAP16=na=new Int16Array(f);e.HEAP32=D=new Int32Array(f);e.HEAPU8=B=new Uint8Array(f);e.HEAPU16=oa=new Uint16Array(f);e.HEAPU32=pa=new Uint32Array(f);e.HEAPF32=qa=new Float32Array(f);e.HEAPF64=E=new Float64Array(f);F=e.asm.ob;sa.unshift(e.asm.nb);G--;e.monitorRunDependencies&&e.monitorRunDependencies(G);0==G&&(null!==xa&&(clearInterval(xa),xa=null),H&&(f=H,H=null,f()))}function b(f){a(f.instance)}function c(f){return Ba().then(function(l){return WebAssembly.instantiate(l,
d)}).then(function(l){return l}).then(f,function(l){x("failed to asynchronously prepare wasm: "+l);z(l)})}var d={a:Gb};G++;e.monitorRunDependencies&&e.monitorRunDependencies(G);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return x("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return y||"function"!=typeof WebAssembly.instantiateStreaming||ya()||I.startsWith("file://")||ea||"function"!=typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
d).then(b,function(l){x("wasm streaming compile failed: "+l);x("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Eb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Eb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.pb).apply(null,arguments)},Ab=e.__sapp_emsc_onpaste=function(){return(Ab=e.__sapp_emsc_onpaste=e.asm.qb).apply(null,arguments)},zb=e.__sapp_html5_get_ask_leave_site=function(){return(zb=e.__sapp_html5_get_ask_leave_site=e.asm.rb).apply(null,arguments)},Bb=e.__sapp_emsc_begin_drop=function(){return(Bb=e.__sapp_emsc_begin_drop=e.asm.sb).apply(null,arguments)},Cb=e.__sapp_emsc_drop=function(){return(Cb=
e.__sapp_emsc_drop=e.asm.tb).apply(null,arguments)},Db=e.__sapp_emsc_end_drop=function(){return(Db=e.__sapp_emsc_end_drop=e.asm.ub).apply(null,arguments)};e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm.vb).apply(null,arguments)};var Hb=e._main=function(){return(Hb=e._main=e.asm.wb).apply(null,arguments)},Fb=e.__saudio_emsc_pull=function(){return(Fb=e.__saudio_emsc_pull=e.asm.xb).apply(null,arguments)};function R(){return(R=e.asm.yb).apply(null,arguments)}
function Da(){return(Da=e.asm.zb).apply(null,arguments)}function Ea(){return(Ea=e.asm.Ab).apply(null,arguments)}function yb(){return(yb=e.asm.Bb).apply(null,arguments)}e.___start_em_js=23400;e.___stop_em_js=31475;var Ib;H=function Jb(){Ib||Kb();Ib||(H=Jb)};function Lb(a=[]){var b=Hb;a.unshift(ca);var c=a.length,d=yb(4*(c+1)),f=d>>2;a.forEach(g=>{D[f++]=xb(g)});D[f]=0;try{var l=b(c,d);wb(l)}catch(g){g instanceof w||"unwind"==g||h(1,g)}}
function Kb(){var a=ba;function b(){if(!Ib&&(Ib=!0,e.calledRun=!0,!ja)){K(sa);K(ta);if(e.onRuntimeInitialized)e.onRuntimeInitialized();Mb&&Lb(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();va.unshift(c)}K(va)}}if(!(0<G)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)wa();K(ra);0<G||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):
b())}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Mb=!0;e.noInitialRun&&(Mb=!1);Kb();
