
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},e),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,u,v;
if(ea){q=l?require("path").dirname(q)+"/":__dirname+"/";var fs,w,ha=()=>{w||(fs=require("fs"),w=require("path"))};fa=(a,b)=>{ha();a=w.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};u=(a,b,c)=>{ha();a=w.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof
x))throw a;});process.on("unhandledRejection",function(a){throw a;});k=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof x||y("exiting due to exception: "+b);process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);
b.send(null);return b.responseText},l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};e.print||console.log.bind(console);var y=e.printErr||console.warn.bind(console);Object.assign(e,aa);aa=null;e.arguments&&(ba=e.arguments);
e.thisProgram&&(ca=e.thisProgram);e.quit&&(k=e.quit);var z;e.wasmBinary&&(z=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!=typeof WebAssembly&&A("no native wasm support detected");var ia,ja=!1,ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function B(a,b){if(a){var c=C,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&ka)a=ka.decode(c.subarray(a,b));else{for(d="";a<b;){var f=c[a++];if(f&128){var h=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var g=c[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}
function D(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function la(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var ma,C,na,oa,E,pa,qa,F,G,ra=[],sa=[],ta=[],ua=[],va=[];function wa(){var a=e.preRun.shift();ra.unshift(a)}var H=0,xa=null,I=null;function A(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";y(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function ya(){return K.startsWith("data:application/octet-stream;base64,")}var K;
K="pacman.wasm";if(!ya()){var za=K;K=e.locateFile?e.locateFile(za,q):q+za}function Aa(){var a=K;try{if(a==K&&z)return new Uint8Array(z);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Ba(){if(!z&&(da||l)){if("function"==typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Aa()});if(u)return new Promise(function(a,b){u(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Aa()})}function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function L(a){for(;0<a.length;)a.shift()(e)}function Ca(a){var b=Da();a();Ea(b)}var Fa=0;function Ga(){for(var a=M.length-1;0<=a;--a)Ha(a);M=[];N=[]}var N=[];function Ia(){if(Fa&&Ja.Ib)for(var a=0;a<N.length;++a){var b=N[a];N.splice(a,1);--a;b.rc.apply(null,b.hc)}}var M=[];function Ha(a){var b=M[a];b.target.removeEventListener(b.Ab,b.bc,b.Bb);M.splice(a,1)}
function O(a){function b(d){++Fa;Ja=a;Ia();a.Db(d);Ia();--Fa}if(a.Cb)a.bc=b,a.target.addEventListener(a.Ab,b,a.Bb),M.push(a),Ka||(ua.push(Ga),Ka=!0);else for(var c=0;c<M.length;++c)M[c].target==a.target&&M[c].Ab==a.Ab&&Ha(c--)}function La(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Ka,Ja,Ma,Na,P,Oa,Pa,Qa,Ra,Sa=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function Q(a){a=2<a?B(a):a;return Sa[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Ta(a){return 0>Sa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Ua(a,b,c,d,f,h){Ma||(Ma=R(256));a={target:Q(a),Ab:h,Cb:d,Db:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Ma;D(La(g.target),C,n+0,128);D(m,C,n+128,128);G.get(d)(f,n,b)&&g.preventDefault()},Bb:c};O(a)}
function Va(a,b,c,d,f,h){Na||(Na=R(176));a={target:Q(a),Ib:!0,Ab:h,Cb:d,Db:function(g){var m=Na;F[m>>3]=g.timeStamp;var n=m>>2;E[n+2]=g.location;E[n+3]=g.ctrlKey;E[n+4]=g.shiftKey;E[n+5]=g.altKey;E[n+6]=g.metaKey;E[n+7]=g.repeat;E[n+8]=g.charCode;E[n+9]=g.keyCode;E[n+10]=g.which;D(g.key||"",C,m+44,32);D(g.code||"",C,m+76,32);D(g.char||"",C,m+108,32);D(g.locale||"",C,m+140,32);G.get(d)(f,m,b)&&g.preventDefault()},Bb:c};O(a)}
function Wa(a,b,c){F[a>>3]=b.timeStamp;a>>=2;E[a+2]=b.screenX;E[a+3]=b.screenY;E[a+4]=b.clientX;E[a+5]=b.clientY;E[a+6]=b.ctrlKey;E[a+7]=b.shiftKey;E[a+8]=b.altKey;E[a+9]=b.metaKey;na[2*a+20]=b.button;na[2*a+21]=b.buttons;E[a+11]=b.movementX;E[a+12]=b.movementY;c=Ta(c);E[a+13]=b.clientX-c.left;E[a+14]=b.clientY-c.top}
function S(a,b,c,d,f,h){P||(P=R(72));a=Q(a);O({target:a,Ib:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Ab:h,Cb:d,Db:function(g){g=g||event;Wa(P,g,a);G.get(d)(f,P,b)&&g.preventDefault()},Bb:c})}function T(a,b,c,d,f){Oa||(Oa=R(260));O({target:a,Ab:f,Cb:d,Db:function(h){h=h||event;var g=Oa,m=document.pointerLockElement||document.Hb||document.Pb||document.Ob;E[g>>2]=!!m;var n=m&&m.id?m.id:"";D(La(m),C,g+4,128);D(n,C,g+132,128);G.get(d)(20,g,b)&&h.preventDefault()},Bb:c})}
function Xa(a,b,c,d,f){O({target:a,Ab:f,Cb:d,Db:function(h){h=h||event;G.get(d)(38,0,b)&&h.preventDefault()},Bb:c})}
function Ya(a,b,c,d){Pa||(Pa=R(36));a=Q(a);O({target:a,Ab:"resize",Cb:d,Db:function(f){f=f||event;if(f.target==a){var h=document.body;if(h){var g=Pa;E[g>>2]=f.detail;E[g+4>>2]=h.clientWidth;E[g+8>>2]=h.clientHeight;E[g+12>>2]=innerWidth;E[g+16>>2]=innerHeight;E[g+20>>2]=outerWidth;E[g+24>>2]=outerHeight;E[g+28>>2]=pageXOffset;E[g+32>>2]=pageYOffset;G.get(d)(10,g,b)&&f.preventDefault()}}},Bb:c})}
function Za(a,b,c,d,f,h){Qa||(Qa=R(1696));a=Q(a);O({target:a,Ib:"touchstart"==h||"touchend"==h,Ab:h,Cb:d,Db:function(g){for(var m,n={},r=g.touches,t=0;t<r.length;++t)m=r[t],m.Rb=m.Sb=0,n[m.identifier]=m;for(t=0;t<g.changedTouches.length;++t)m=g.changedTouches[t],m.Rb=1,n[m.identifier]=m;for(t=0;t<g.targetTouches.length;++t)n[g.targetTouches[t].identifier].Sb=1;r=Qa;F[r>>3]=g.timeStamp;var p=r>>2;E[p+3]=g.ctrlKey;E[p+4]=g.shiftKey;E[p+5]=g.altKey;E[p+6]=g.metaKey;p+=7;var J=Ta(a),db=0;for(t in n)if(m=
n[t],E[p]=m.identifier,E[p+1]=m.screenX,E[p+2]=m.screenY,E[p+3]=m.clientX,E[p+4]=m.clientY,E[p+5]=m.pageX,E[p+6]=m.pageY,E[p+7]=m.Rb,E[p+8]=m.Sb,E[p+9]=m.clientX-J.left,E[p+10]=m.clientY-J.top,p+=13,31<++db)break;E[r+8>>2]=db;G.get(d)(f,r,b)&&g.preventDefault()},Bb:c})}function $a(a,b,c,d,f,h){a={target:Q(a),Ab:h,Cb:d,Db:function(g){g=g||event;G.get(d)(f,0,b)&&g.preventDefault()},Bb:c};O(a)}
function ab(a,b,c,d){Ra||(Ra=R(104));O({target:a,Ib:!0,Ab:"wheel",Cb:d,Db:function(f){f=f||event;var h=Ra;Wa(h,f,a);F[h+72>>3]=f.deltaX;F[h+80>>3]=f.deltaY;F[h+88>>3]=f.deltaZ;E[h+96>>2]=f.deltaMode;G.get(d)(9,h,b)&&f.preventDefault()},Bb:c})}
function bb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,h){b.drawArraysInstancedANGLE(c,d,f,h)},a.drawElementsInstanced=function(c,d,f,h,g){b.drawElementsInstancedANGLE(c,d,f,h,g)})}
function cb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function eb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function fb(a){a.mc=a.getExtension("WEBGL_multi_draw")}
var gb=1,hb=[],U=[],ib=[],V=[],W=[],X=[],jb=[],kb={};function Y(a){lb||(lb=a)}function mb(a){for(var b=gb++,c=a.length;c<b;c++)a[c]=null;return b}function nb(a,b){a.Hb||(a.Hb=a.getContext,a.getContext=function(d,f){f=a.Hb(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?ob(c,b):0}function ob(a,b){var c=mb(jb),d={kc:c,attributes:b,version:b.ec,Mb:a};a.canvas&&(a.canvas.fc=d);jb[c]=d;("undefined"==typeof b.Qb||b.Qb)&&pb(d);return c}
function pb(a){a||(a=qb);if(!a.dc){a.dc=!0;var b=a.Mb;bb(b);cb(b);eb(b);b.jc=b.getExtension("EXT_disjoint_timer_query");fb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var lb,qb,rb=["default","low-power","high-performance"];function sb(a,b,c,d){for(var f=0;f<a;f++){var h=Z[c](),g=h&&mb(d);h?(h.name=g,d[g]=h):Y(1282);E[b+4*f>>2]=g}}
function tb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)E[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Y(1280);y("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Y(1280);y("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}E[b>>2]=c}else Y(1281)}function ub(a){var b=la(a)+1,c=R(b);D(a,C,c,b);return c}
function vb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function wb(a){if(!noExitRuntime){if(e.onExit)e.onExit(a);ja=!0}k(a,new x(a))}function xb(a){var b=la(a)+1,c=yb(b);D(a,ma,c,b);return c}
var Z,Gb={L:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},da:function(a,b,c){a=Q(a);if(!a)return-4;a=Ta(a);F[b>>3]=a.width;F[c>>3]=a.height;return 0},Za:function(a,b,c){C.copyWithin(a,b,b+c)},Ta:function(a,b){function c(d){G.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ya:function(){A("OOM")},N:function(a,b,c,d){Ua(a,b,c,d,12,"blur");return 0},I:function(a,b,c){a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},O:function(a,b,c,d){Ua(a,b,c,d,
13,"focus");return 0},X:function(a,b,c,d){Va(a,b,c,d,2,"keydown");return 0},V:function(a,b,c,d){Va(a,b,c,d,1,"keypress");return 0},W:function(a,b,c,d){Va(a,b,c,d,3,"keyup");return 0},r:function(a,b,c,d){S(a,b,c,d,5,"mousedown");return 0},_:function(a,b,c,d){S(a,b,c,d,33,"mouseenter");return 0},Z:function(a,b,c,d){S(a,b,c,d,34,"mouseleave");return 0},aa:function(a,b,c,d){S(a,b,c,d,8,"mousemove");return 0},ca:function(a,b,c,d){S(a,b,c,d,6,"mouseup");return 0},Q:function(a,b,c,d){if(!document||!document.body||
!(document.body.requestPointerLock||document.body.Hb||document.body.Pb||document.body.Ob))return-1;a=Q(a);if(!a)return-4;T(a,b,c,d,"pointerlockchange");T(a,b,c,d,"mozpointerlockchange");T(a,b,c,d,"webkitpointerlockchange");T(a,b,c,d,"mspointerlockchange");return 0},P:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Hb||document.body.Pb||document.body.Ob))return-1;a=Q(a);if(!a)return-4;Xa(a,b,c,d,"pointerlockerror");Xa(a,b,c,d,"mozpointerlockerror");Xa(a,b,c,d,"webkitpointerlockerror");
Xa(a,b,c,d,"mspointerlockerror");return 0},Xa:function(a,b,c,d){Ya(a,b,c,d);return 0},R:function(a,b,c,d){Za(a,b,c,d,25,"touchcancel");return 0},S:function(a,b,c,d){Za(a,b,c,d,23,"touchend");return 0},T:function(a,b,c,d){Za(a,b,c,d,24,"touchmove");return 0},U:function(a,b,c,d){Za(a,b,c,d,22,"touchstart");return 0},M:function(a,b,c,d){$a(a,b,c,d,31,"webglcontextlost");return 0},K:function(a,b,c,d){$a(a,b,c,d,32,"webglcontextrestored");return 0},Y:function(a,b,c,d){a=Q(a);return"undefined"!=typeof a.onwheel?
(ab(a,b,c,d),0):-1},D:function(a,b){b>>=2;b={alpha:!!E[b],depth:!!E[b+1],stencil:!!E[b+2],antialias:!!E[b+3],premultipliedAlpha:!!E[b+4],preserveDrawingBuffer:!!E[b+5],powerPreference:rb[E[b+6]],failIfMajorPerformanceCaveat:!!E[b+7],ec:E[b+8],lc:E[b+9],Qb:E[b+10],cc:E[b+11],nc:E[b+12],oc:E[b+13]};a=Q(a);return!a||b.cc?0:nb(a,b)},sa:function(a,b){a=jb[a];b=B(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&bb(Z);"OES_vertex_array_object"==b&&cb(Z);"WEBGL_draw_buffers"==b&&eb(Z);
"WEBGL_multi_draw"==b&&fb(Z);return!!a.Mb.getExtension(b)},Ha:function(a){a>>=2;for(var b=0;14>b;++b)E[a+b]=0;E[a]=E[a+1]=E[a+3]=E[a+4]=E[a+8]=E[a+10]=1},za:function(a){qb=jb[a];e.ic=Z=qb&&qb.Mb;return!a||Z?0:-5},p:function(a){Z.activeTexture(a)},G:function(a,b){Z.attachShader(U[a],X[b])},b:function(a,b){Z.bindBuffer(a,hb[b])},f:function(a,b){Z.bindFramebuffer(a,ib[b])},La:function(a,b){Z.bindRenderbuffer(a,V[b])},g:function(a,b){Z.bindTexture(a,W[b])},v:function(a,b,c,d){Z.blendColor(a,b,c,d)},w:function(a,
b){Z.blendEquationSeparate(a,b)},x:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},Na:function(a,b,c,d){Z.bufferData(a,c?C.subarray(c,c+b):b,d)},H:function(a,b,c,d){Z.bufferSubData(a,b,C.subarray(d,d+c))},A:function(a){return Z.checkFramebufferStatus(a)},va:function(a){Z.clear(a)},ya:function(a,b,c,d){Z.clearColor(a,b,c,d)},xa:function(a){Z.clearDepth(a)},wa:function(a){Z.clearStencil(a)},h:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},$a:function(a){Z.compileShader(X[a])},Ia:function(a,b,c,d,f,
h,g,m){Z.compressedTexImage2D(a,b,c,d,f,h,m?C.subarray(m,m+g):null)},Fa:function(){var a=mb(U),b=Z.createProgram();b.name=a;b.Lb=b.Jb=b.Kb=0;b.Nb=1;U[a]=b;return a},bb:function(a){var b=mb(X);X[b]=Z.createShader(a);return b},u:function(a){Z.cullFace(a)},Pa:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=hb[d];f&&(Z.deleteBuffer(f),f.name=0,hb[d]=null)}},o:function(a,b){for(var c=0;c<a;++c){var d=E[b+4*c>>2],f=ib[d];f&&(Z.deleteFramebuffer(f),f.name=0,ib[d]=null)}},J:function(a){if(a){var b=
U[a];b?(Z.deleteProgram(b),b.name=0,U[a]=null):Y(1281)}},ba:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=V[d];f&&(Z.deleteRenderbuffer(f),f.name=0,V[d]=null)}},n:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},eb:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=W[d];f&&(Z.deleteTexture(f),f.name=0,W[d]=null)}},k:function(a){Z.depthFunc(a)},l:function(a){Z.depthMask(!!a)},a:function(a){Z.disable(a)},s:function(a){Z.disableVertexAttribArray(a)},la:function(a,b,
c){Z.drawArrays(a,b,c)},ma:function(a,b,c,d){Z.drawArraysInstanced(a,b,c,d)},na:function(a,b,c,d){Z.drawElements(a,b,c,d)},oa:function(a,b,c,d,f){Z.drawElementsInstanced(a,b,c,d,f)},d:function(a){Z.enable(a)},pa:function(a){Z.enableVertexAttribArray(a)},m:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,V[d])},B:function(a,b,c,d,f){Z.framebufferTexture2D(a,b,c,W[d],f)},t:function(a){Z.frontFace(a)},Oa:function(a,b){sb(a,b,"createBuffer",hb)},C:function(a,b){sb(a,b,"createFramebuffer",ib)},Ma:function(a,
b){sb(a,b,"createRenderbuffer",V)},Ja:function(a,b){sb(a,b,"createTexture",W)},Ba:function(a,b){return Z.getAttribLocation(U[a],B(b))},c:function(a,b){tb(a,b)},Da:function(a,b,c,d){a=Z.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,C,d,b):0;c&&(E[c>>2]=b)},F:function(a,b,c){if(c)if(a>=gb)Y(1281);else if(a=U[a],35716==b)a=Z.getProgramInfoLog(a),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b){if(!a.Lb)for(b=0;b<Z.getProgramParameter(a,35718);++b)a.Lb=Math.max(a.Lb,
Z.getActiveUniform(a,b).name.length+1);E[c>>2]=a.Lb}else if(35722==b){if(!a.Jb)for(b=0;b<Z.getProgramParameter(a,35721);++b)a.Jb=Math.max(a.Jb,Z.getActiveAttrib(a,b).name.length+1);E[c>>2]=a.Jb}else if(35381==b){if(!a.Kb)for(b=0;b<Z.getProgramParameter(a,35382);++b)a.Kb=Math.max(a.Kb,Z.getActiveUniformBlockName(a,b).length+1);E[c>>2]=a.Kb}else E[c>>2]=Z.getProgramParameter(a,b);else Y(1281)},_a:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,C,d,b):0;c&&(E[c>>
2]=b)},$:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(X[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},Qa:function(a){var b=kb[a];if(!b){switch(a){case 7939:b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ub(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||Y(1280);b=b&&ub(b);break;case 7938:b=ub("OpenGL ES 2.0 ("+
Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ub(b);break;default:Y(1280)}kb[a]=b}return b},E:function(a,b){b=B(b);if(a=U[a]){var c=a,d=c.Gb,f=c.$b,h;if(!d)for(c.Gb=d={},c.Zb={},h=0;h<Z.getProgramParameter(c,35718);++h){var g=Z.getActiveUniform(c,h);var m=g.name;g=g.size;var n=vb(m);n=0<n?m.slice(0,n):m;var r=c.Nb;c.Nb+=g;f[n]=[g,r];for(m=
0;m<g;++m)d[r]=m,c.Zb[r++]=n}c=a.Gb;d=0;f=b;h=vb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,f=b.slice(0,h));if((f=a.$b[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||Z.getUniformLocation(a,b)))return d}else Y(1281);return-1},Ea:function(a){a=U[a];Z.linkProgram(a);a.Gb=0;a.$b={}},y:function(a,b){Z.polygonOffset(a,b)},Ka:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},Aa:function(a,b,c,d){Z.scissor(a,b,c,d)},ab:function(a,b,c,d){for(var f="",h=0;h<b;++h){var g=d?E[d+4*h>>2]:-1;f+=B(E[c+4*h>>2],0>g?void 0:g)}Z.shaderSource(X[a],
f)},db:function(a,b,c){Z.stencilFunc(a,b,c)},ua:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},j:function(a){Z.stencilMask(a)},cb:function(a,b,c){Z.stencilOp(a,b,c)},ta:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},Ga:function(a,b,c,d,f,h,g,m,n){var r=Z,t=r.texImage2D;if(n){var p=m-5120;p=1==p?C:4==p?E:6==p?qa:5==p||28922==p?pa:oa;var J=31-Math.clz32(p.BYTES_PER_ELEMENT);n=p.subarray(n>>J,n+f*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-6402]||1)*(1<<J)+4-1&-4)>>J)}else n=null;t.call(r,a,b,c,d,f,h,g,
m,n)},e:function(a,b,c){Z.texParameteri(a,b,c)},Ca:function(a,b){var c=Z,d=c.uniform1i;var f=Z.ac;if(f){var h=f.Gb[a];"number"==typeof h&&(f.Gb[a]=h=Z.getUniformLocation(f,f.Zb[a]+(0<h?"["+h+"]":"")));a=h}else Y(1282),a=void 0;d.call(c,a,b)},i:function(a){a=U[a];Z.useProgram(a);Z.ac=a},qa:function(a,b){Z.vertexAttribDivisor(a,b)},ra:function(a,b,c,d,f,h){Z.vertexAttribPointer(a,b,c,!!d,f,h)},z:function(a,b,c,d){Z.viewport(a,b,c,d)},Wa:function(){e.Tb=function(a){0!=zb()&&(a.preventDefault(),a.returnValue=
" ")};window.addEventListener("beforeunload",e.Tb)},Va:function(){e.Yb=function(a){var b=a.clipboardData.getData("text");Ca(()=>{var c=xb(b);Ab(c)})};window.addEventListener("paste",e.Yb)},Ua:function(a){e.pc=[];a=B(a);a=document.getElementById(a);e.Ub=function(b){b.stopPropagation();b.preventDefault()};e.Vb=function(b){b.stopPropagation();b.preventDefault()};e.Wb=function(b){b.stopPropagation();b.preventDefault()};e.Xb=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;
e.qc=c;Bb(c.length);var d;for(d=0;d<c.length;d++)Ca(()=>{var f=xb(c[d].name);Cb(d,f)});Db(b.clientX,b.clientY)};a.addEventListener("dragenter",e.Ub,!1);a.addEventListener("dragleave",e.Vb,!1);a.addEventListener("dragover",e.Wb,!1);a.addEventListener("drop",e.Xb,!1)},Sa:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},hb:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",
function(){Eb()});document.body.append(a)},gb:function(){document.getElementById("_sokol_app_input_element").focus()},ib:function(a){a=B(a);e.Fb=document.getElementById(a);e.Fb||console.log("sokol_app.h: invalid target:"+a);e.Fb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},ga:function(){window.removeEventListener("beforeunload",e.Tb)},fa:function(){window.removeEventListener("paste",e.Yb)},ea:function(a){a=B(a);a=document.getElementById(a);a.removeEventListener("dragenter",
e.Ub);a.removeEventListener("dragleave",e.Vb);a.removeEventListener("dragover",e.Wb);a.removeEventListener("drop",e.Xb)},q:function(){e.Fb&&e.Fb.requestPointerLock&&e.Fb.requestPointerLock()},Ra:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(C.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},
fb:function(){document.getElementById("_sokol_app_input_element").blur()},ia:function(){return e.Eb?e.Eb.bufferSize:0},ka:function(a,b,c){e.zb=null;e.Eb=null;"undefined"!==typeof AudioContext?e.zb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?e.zb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(e.zb=null,console.log("sokol_audio.h: no WebAudio support"));return e.zb?(console.log("sokol_audio.h: sample rate ",e.zb.sampleRate),e.Eb=
e.zb.createScriptProcessor(c,0,b),e.Eb.onaudioprocess=function(d){var f=d.outputBuffer.length,h=Fb(f);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),r=0;r<f;r++)n[r]=qa[(h>>2)+(g*r+m)]},e.Eb.connect(e.zb.destination),a=function(){e.zb&&"suspended"===e.zb.state&&e.zb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ja:function(){return e.zb?
e.zb.sampleRate:0},ha:function(){null!==e.zb&&(e.Eb&&e.Eb.disconnect(),e.zb.close(),e.zb=null,e.Eb=null)}};
(function(){function a(f){e.asm=f.exports;ia=e.asm.jb;f=ia.buffer;e.HEAP8=ma=new Int8Array(f);e.HEAP16=na=new Int16Array(f);e.HEAP32=E=new Int32Array(f);e.HEAPU8=C=new Uint8Array(f);e.HEAPU16=oa=new Uint16Array(f);e.HEAPU32=pa=new Uint32Array(f);e.HEAPF32=qa=new Float32Array(f);e.HEAPF64=F=new Float64Array(f);G=e.asm.lb;sa.unshift(e.asm.kb);H--;e.monitorRunDependencies&&e.monitorRunDependencies(H);0==H&&(null!==xa&&(clearInterval(xa),xa=null),I&&(f=I,I=null,f()))}function b(f){a(f.instance)}function c(f){return Ba().then(function(h){return WebAssembly.instantiate(h,
d)}).then(function(h){return h}).then(f,function(h){y("failed to asynchronously prepare wasm: "+h);A(h)})}var d={a:Gb};H++;e.monitorRunDependencies&&e.monitorRunDependencies(H);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return y("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return z||"function"!=typeof WebAssembly.instantiateStreaming||ya()||K.startsWith("file://")||ea||"function"!=typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.kb).apply(null,arguments)};
var Eb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Eb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.mb).apply(null,arguments)},Ab=e.__sapp_emsc_onpaste=function(){return(Ab=e.__sapp_emsc_onpaste=e.asm.nb).apply(null,arguments)},zb=e.__sapp_html5_get_ask_leave_site=function(){return(zb=e.__sapp_html5_get_ask_leave_site=e.asm.ob).apply(null,arguments)},Bb=e.__sapp_emsc_begin_drop=function(){return(Bb=e.__sapp_emsc_begin_drop=e.asm.pb).apply(null,arguments)},Cb=e.__sapp_emsc_drop=function(){return(Cb=
e.__sapp_emsc_drop=e.asm.qb).apply(null,arguments)},Db=e.__sapp_emsc_end_drop=function(){return(Db=e.__sapp_emsc_end_drop=e.asm.rb).apply(null,arguments)};e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm.sb).apply(null,arguments)};e._main=function(){return(e._main=e.asm.tb).apply(null,arguments)};
var R=e._malloc=function(){return(R=e._malloc=e.asm.ub).apply(null,arguments)},Fb=e.__saudio_emsc_pull=function(){return(Fb=e.__saudio_emsc_pull=e.asm.vb).apply(null,arguments)},Da=e.stackSave=function(){return(Da=e.stackSave=e.asm.wb).apply(null,arguments)},Ea=e.stackRestore=function(){return(Ea=e.stackRestore=e.asm.xb).apply(null,arguments)},yb=e.stackAlloc=function(){return(yb=e.stackAlloc=e.asm.yb).apply(null,arguments)};e.___start_em_js=23236;e.___stop_em_js=31128;var Hb;
I=function Ib(){Hb||Jb();Hb||(I=Ib)};function Kb(a){var b=e._main;a=a||[];a.unshift(ca);var c=a.length,d=yb(4*(c+1)),f=d>>2;a.forEach(g=>{E[f++]=xb(g)});E[f]=0;try{var h=b(c,d);wb(h)}catch(g){g instanceof x||"unwind"==g||k(1,g)}}
function Jb(){function a(){if(!Hb&&(Hb=!0,e.calledRun=!0,!ja)){L(sa);L(ta);if(e.onRuntimeInitialized)e.onRuntimeInitialized();Lb&&Kb(b);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var c=e.postRun.shift();va.unshift(c)}L(va)}}var b=b||ba;if(!(0<H)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)wa();L(ra);0<H||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},
1)):a())}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Lb=!0;e.noInitialRun&&(Lb=!1);Jb();
