
var d;d||(d=typeof Module !== 'undefined' ? Module : {});var h={},l;for(l in d)d.hasOwnProperty(l)&&(h[l]=d[l]);var r=[],aa="./this.program";function t(a,b){throw b;}var u=!1,v=!1,ba=!1,ca=!1;u="object"===typeof window;v="function"===typeof importScripts;ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!u&&!ba&&!v;var w="",da,x,ea,fa;
if(ba)w=v?require("path").dirname(w)+"/":__dirname+"/",da=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);return ea.readFileSync(a,b?null:"utf8")},x=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),r=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=d),process.on("uncaughtException",function(a){if(!(a instanceof ha))throw a;}),process.on("unhandledRejection",
z),t=function(a){process.exit(a)},d.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),x=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r=scriptArgs:"undefined"!=typeof arguments&&(r=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(u||v)v?w=self.location.href:"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src),w=0!==w.indexOf("blob:")?w.substr(0,w.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(x=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
d.print||console.log.bind(console);var A=d.printErr||console.warn.bind(console);for(l in h)h.hasOwnProperty(l)&&(d[l]=h[l]);h=null;d.arguments&&(r=d.arguments);d.thisProgram&&(aa=d.thisProgram);d.quit&&(t=d.quit);var B;d.wasmBinary&&(B=d.wasmBinary);var noExitRuntime;d.noExitRuntime&&(noExitRuntime=d.noExitRuntime);"object"!==typeof WebAssembly&&z("no native wasm support detected");var ia,ja=!1;function assert(a,b){a||z("Assertion failed: "+b)}
function ka(a){var b=d["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}function la(a,b,c){var e={string:function(m){var p=0;if(null!==m&&void 0!==m&&0!==m){var q=(m.length<<2)+1;p=C(q);D(m,E,p,q)}return p},array:function(m){var p=C(m.length);ma.set(m,p);return p}};a=ka(a);var f=[],k=0;if(c)for(var g=0;g<c.length;g++){var n=e[b[g]];n?(0===k&&(k=na()),f[g]=n(c[g])):f[g]=c[g]}a.apply(null,f);0!==k&&oa(k)}
var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b){if(a){var c=E,e=a+b;for(b=a;c[b]&&!(b>=e);)++b;if(16<b-a&&c.subarray&&pa)a=pa.decode(c.subarray(a,b));else{for(e="";a<b;){var f=c[a++];if(f&128){var k=c[a++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|k);else{var g=c[a++]&63;f=224==(f&240)?(f&15)<<12|k<<6|g:(f&7)<<18|k<<12|g<<6|c[a++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}a=e}}else a="";return a}
function D(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var k=0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var n=a.charCodeAt(++k);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(c>=e)break;b[c++]=g}else{if(2047>=g){if(c+1>=e)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=e)break;b[c++]=224|g>>12}else{if(c+3>=e)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function qa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function ra(a){var b=qa(a)+1,c=C(b);D(a,ma,c,b);return c}var ma,E,sa,ta,G,ua,va,H,I,wa=[],xa=[],ya=[],za=[],Aa=[];function Ba(){var a=d.preRun.shift();wa.unshift(a)}var J=0,Ca=null,K=null;d.preloadedImages={};d.preloadedAudios={};
function z(a){if(d.onAbort)d.onAbort(a);A(a);ja=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Da(a){var b=L;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ea(){return Da("data:application/octet-stream;base64,")}var L="pacman.wasm";if(!Ea()){var Fa=L;L=d.locateFile?d.locateFile(Fa,w):w+Fa}
function Ga(){try{if(B)return new Uint8Array(B);if(x)return x(L);throw"both async and sync fetching of the wasm failed";}catch(a){z(a)}}function Ha(){return B||!u&&!v||"function"!==typeof fetch||Da("file://")?Promise.resolve().then(Ga):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ga()})}
function Ia(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.oc;"number"===typeof c?void 0===b.Zb?I.get(c)():I.get(c)(b.Zb):c(void 0===b.Zb?null:b.Zb)}}}var Ja=0;function Ka(){for(var a=M.length-1;0<=a;--a)La(a);M=[];Ma=[]}var Ma=[];function Na(){if(Ja&&Oa.Xb)for(var a=0;a<Ma.length;++a){var b=Ma[a];Ma.splice(a,1);--a;b.Ec.apply(null,b.uc)}}var M=[];function La(a){var b=M[a];b.target.removeEventListener(b.Pb,b.mc,b.Qb);M.splice(a,1)}
function N(a){function b(e){++Ja;Oa=a;Na();a.Tb(e);Na();--Ja}if(a.Sb)a.mc=b,a.target.addEventListener(a.Pb,b,a.Qb),M.push(a),Pa||(za.push(Ka),Pa=!0);else for(var c=0;c<M.length;++c)M[c].target==a.target&&M[c].Pb==a.Pb&&La(c--)}var Pa,Oa,Qa,Ra,Sa,Ta,Ua,Va,Wa=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function O(a){a=2<a?F(a):a;return Wa[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Xa(a){return 0>Wa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Ya(a,b,c,e,f,k){Qa||(Qa=P(164));a={target:O(a),Xb:!0,Pb:k,Sb:e,Tb:function(g){var n=Qa,m=n>>2;G[m]=g.location;G[m+1]=g.ctrlKey;G[m+2]=g.shiftKey;G[m+3]=g.altKey;G[m+4]=g.metaKey;G[m+5]=g.repeat;G[m+6]=g.charCode;G[m+7]=g.keyCode;G[m+8]=g.which;D(g.key||"",E,n+36,32);D(g.code||"",E,n+68,32);D(g.char||"",E,n+100,32);D(g.locale||"",E,n+132,32);I.get(e)(f,n,b)&&g.preventDefault()},Qb:c};N(a)}
function Za(a,b,c){a>>=2;G[a]=b.screenX;G[a+1]=b.screenY;G[a+2]=b.clientX;G[a+3]=b.clientY;G[a+4]=b.ctrlKey;G[a+5]=b.shiftKey;G[a+6]=b.altKey;G[a+7]=b.metaKey;sa[2*a+16]=b.button;sa[2*a+17]=b.buttons;G[a+9]=b.movementX;G[a+10]=b.movementY;c=Xa(c);G[a+11]=b.clientX-c.left;G[a+12]=b.clientY-c.top}function Q(a,b,c,e,f,k){Ra||(Ra=P(64));a=O(a);N({target:a,Xb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Pb:k,Sb:e,Tb:function(g){g=g||event;Za(Ra,g,a);I.get(e)(f,Ra,b)&&g.preventDefault()},Qb:c})}
function $a(a,b,c,e,f){Sa||(Sa=P(260));N({target:a,Pb:f,Sb:e,Tb:function(k){k=k||event;var g=Sa,n=document.pointerLockElement||document.ac||document.cc||document.bc;G[g>>2]=!!n;var m=n&&n.id?n.id:"";D(n?n==window?"#window":n==screen?"#screen":n&&n.nodeName?n.nodeName:"":"",E,g+4,128);D(m,E,g+132,128);I.get(e)(20,g,b)&&k.preventDefault()},Qb:c})}function ab(a,b,c,e,f){N({target:a,Pb:f,Sb:e,Tb:function(k){k=k||event;I.get(e)(38,0,b)&&k.preventDefault()},Qb:c})}
function bb(a,b,c,e){Ta||(Ta=P(36));a=O(a);N({target:a,Pb:"resize",Sb:e,Tb:function(f){f=f||event;if(f.target==a){var k=document.body;if(k){var g=Ta;G[g>>2]=f.detail;G[g+4>>2]=k.clientWidth;G[g+8>>2]=k.clientHeight;G[g+12>>2]=innerWidth;G[g+16>>2]=innerHeight;G[g+20>>2]=outerWidth;G[g+24>>2]=outerHeight;G[g+28>>2]=pageXOffset;G[g+32>>2]=pageYOffset;I.get(e)(10,g,b)&&f.preventDefault()}}},Qb:c})}
function cb(a,b,c,e,f,k){Ua||(Ua=P(1684));a=O(a);N({target:a,Xb:"touchstart"==k||"touchend"==k,Pb:k,Sb:e,Tb:function(g){for(var n={},m=g.touches,p=0;p<m.length;++p){var q=m[p];n[q.identifier]=q}m=g.changedTouches;for(p=0;p<m.length;++p)q=m[p],q.qc=1,n[q.identifier]=q;m=g.targetTouches;for(p=0;p<m.length;++p)n[m[p].identifier].sc=1;m=Ua;q=m>>2;G[q+1]=g.ctrlKey;G[q+2]=g.shiftKey;G[q+3]=g.altKey;G[q+4]=g.metaKey;q+=5;var fb=Xa(a),gb=0;for(p in n){var y=n[p];G[q]=y.identifier;G[q+1]=y.screenX;G[q+2]=
y.screenY;G[q+3]=y.clientX;G[q+4]=y.clientY;G[q+5]=y.pageX;G[q+6]=y.pageY;G[q+7]=y.qc;G[q+8]=y.sc;G[q+9]=y.clientX-fb.left;G[q+10]=y.clientY-fb.top;q+=13;if(31<++gb)break}G[m>>2]=gb;I.get(e)(f,m,b)&&g.preventDefault()},Qb:c})}function db(a,b,c,e,f,k){a={target:O(a),Pb:k,Sb:e,Tb:function(g){g=g||event;I.get(e)(f,0,b)&&g.preventDefault()},Qb:c};N(a)}
function eb(a,b,c,e){Va||(Va=P(96));N({target:a,Xb:!0,Pb:"wheel",Sb:e,Tb:function(f){f=f||event;var k=Va;Za(k,f,a);H[k+64>>3]=f.deltaX;H[k+72>>3]=f.deltaY;H[k+80>>3]=f.deltaZ;G[k+88>>2]=f.deltaMode;I.get(e)(9,k,b)&&f.preventDefault()},Qb:c})}
function hb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,f,k){b.drawArraysInstancedANGLE(c,e,f,k)},a.drawElementsInstanced=function(c,e,f,k,g){b.drawElementsInstancedANGLE(c,e,f,k,g)})}
function ib(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function jb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}function kb(a){a.zc=a.getExtension("WEBGL_multi_draw")}
var lb=1,mb=[],R=[],nb=[],S=[],T=[],U=[],V=[],ob=[],W={},pb={};function X(a){qb||(qb=a)}function Y(a){for(var b=lb++,c=a.length;c<b;c++)a[c]=null;return b}function rb(a){a||(a=sb);if(!a.pc){a.pc=!0;var b=a.Yb;hb(b);ib(b);jb(b);b.wc=b.getExtension("EXT_disjoint_timer_query");kb(b);(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var qb,sb,tb=["default","low-power","high-performance"];
function ub(a,b,c,e){for(var f=0;f<a;f++){var k=Z[c](),g=k&&Y(e);k?(k.name=g,e[g]=k):X(1282);G[b+4*f>>2]=g}}
function vb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var e=Z.getParameter(34467);c=e?e.length:0}if(void 0===c)switch(e=Z.getParameter(a),typeof e){case "number":c=e;break;case "boolean":c=e?1:0;break;case "string":X(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:X(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||
e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)G[b+4*a>>2]=e[a];return}try{c=e.name|0}catch(f){X(1280);A("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:X(1280);A("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+e+" of type "+typeof e+"!");return}G[b>>2]=c}else X(1281)}function wb(a){var b=qa(a)+1,c=P(b);D(a,E,c,b);return c}
function xb(a,b,c,e,f){a-=5120;a=1==a?E:4==a?G:6==a?va:5==a||28922==a?ua:ta;var k=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>k,f+e*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<k)+4-1&-4)>>k)}var Z;xa.push({oc:function(){yb()}});
var Eb={L:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},ba:function(a,b,c){a=O(a);if(!a)return-4;a=Xa(a);H[b>>3]=a.width;H[c>>3]=a.height;return 0},Sa:function(a,b,c){E.copyWithin(a,b,b+c)},Ba:function(a,b){function c(e){I.get(a)(e,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ta:function(){z("OOM")},I:function(a,b,c){a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},U:function(a,b,c,e){Ya(a,b,c,e,2,"keydown");return 0},S:function(a,b,c,e){Ya(a,b,c,e,
1,"keypress");return 0},T:function(a,b,c,e){Ya(a,b,c,e,3,"keyup");return 0},_:function(a,b,c,e){Q(a,b,c,e,5,"mousedown");return 0},X:function(a,b,c,e){Q(a,b,c,e,33,"mouseenter");return 0},W:function(a,b,c,e){Q(a,b,c,e,34,"mouseleave");return 0},Y:function(a,b,c,e){Q(a,b,c,e,8,"mousemove");return 0},Z:function(a,b,c,e){Q(a,b,c,e,6,"mouseup");return 0},N:function(a,b,c,e){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ac||document.body.cc||document.body.bc))return-1;
a=O(a);if(!a)return-4;$a(a,b,c,e,"pointerlockchange");$a(a,b,c,e,"mozpointerlockchange");$a(a,b,c,e,"webkitpointerlockchange");$a(a,b,c,e,"mspointerlockchange");return 0},M:function(a,b,c,e){if(!document||!(document.body.requestPointerLock||document.body.ac||document.body.cc||document.body.bc))return-1;a=O(a);if(!a)return-4;ab(a,b,c,e,"pointerlockerror");ab(a,b,c,e,"mozpointerlockerror");ab(a,b,c,e,"webkitpointerlockerror");ab(a,b,c,e,"mspointerlockerror");return 0},Pa:function(a,b,c,e){bb(a,b,c,
e);return 0},O:function(a,b,c,e){cb(a,b,c,e,25,"touchcancel");return 0},P:function(a,b,c,e){cb(a,b,c,e,23,"touchend");return 0},Q:function(a,b,c,e){cb(a,b,c,e,24,"touchmove");return 0},R:function(a,b,c,e){cb(a,b,c,e,22,"touchstart");return 0},K:function(a,b,c,e){db(a,b,c,e,31,"webglcontextlost");return 0},J:function(a,b,c,e){db(a,b,c,e,32,"webglcontextrestored");return 0},V:function(a,b,c,e){a=O(a);return"undefined"!==typeof a.onwheel?(eb(a,b,c,e),0):-1},$:function(a,b){b>>=2;b={alpha:!!G[b],depth:!!G[b+
1],stencil:!!G[b+2],antialias:!!G[b+3],premultipliedAlpha:!!G[b+4],preserveDrawingBuffer:!!G[b+5],powerPreference:tb[G[b+6]],failIfMajorPerformanceCaveat:!!G[b+7],rc:G[b+8],yc:G[b+9],dc:G[b+10],nc:G[b+11],Ac:G[b+12],Bc:G[b+13]};a=O(a);if(!a||b.nc)b=0;else if(a=a.getContext("webgl",b)){var c=Y(ob),e={xc:c,attributes:b,version:b.rc,Yb:a};a.canvas&&(a.canvas.tc=e);ob[c]=e;("undefined"===typeof b.dc||b.dc)&&rb(e);b=c}else b=0;return b},Qa:function(a,b){a=ob[a];b=F(b);0==b.indexOf("GL_")&&(b=b.substr(3));
"ANGLE_instanced_arrays"==b&&hb(Z);"OES_vertex_array_object"==b&&ib(Z);"WEBGL_draw_buffers"==b&&jb(Z);"WEBGL_multi_draw"==b&&kb(Z);return!!a.Yb.getExtension(b)},Ua:function(a){a>>=2;for(var b=0;14>b;++b)G[a+b]=0;G[a]=G[a+1]=G[a+3]=G[a+4]=G[a+8]=G[a+10]=1},Ra:function(a){sb=ob[a];d.vc=Z=sb&&sb.Yb;return!a||Z?0:-5},G:function(a){Z.activeTexture(a)},w:function(a,b){Z.attachShader(R[a],V[b])},e:function(a,b){Z.bindBuffer(a,mb[b])},f:function(a,b){Z.bindFramebuffer(a,nb[b])},ta:function(a,b){Z.bindRenderbuffer(a,
S[b])},g:function(a,b){Z.bindTexture(a,T[b])},B:function(a,b,c,e){Z.blendColor(a,b,c,e)},C:function(a,b){Z.blendEquationSeparate(a,b)},D:function(a,b,c,e){Z.blendFuncSeparate(a,b,c,e)},wa:function(a,b,c,e){Z.bufferData(a,c?E.subarray(c,c+b):b,e)},x:function(a,b,c,e){Z.bufferSubData(a,b,E.subarray(e,e+c))},r:function(a){return Z.checkFramebufferStatus(a)},ab:function(a){Z.clear(a)},ca:function(a,b,c,e){Z.clearColor(a,b,c,e)},cb:function(a){Z.clearDepth(a)},bb:function(a){Z.clearStencil(a)},l:function(a,
b,c,e){Z.colorMask(!!a,!!b,!!c,!!e)},ha:function(a){Z.compileShader(V[a])},qa:function(a,b,c,e,f,k,g,n){Z.compressedTexImage2D(a,b,c,e,f,k,n?E.subarray(n,n+g):null)},oa:function(){var a=Y(R),b=Z.createProgram();b.name=a;R[a]=b;return a},ja:function(a){var b=Y(V);V[b]=Z.createShader(a);return b},y:function(a){Z.cullFace(a)},Da:function(a,b){for(var c=0;c<a;c++){var e=G[b+4*c>>2],f=mb[e];f&&(Z.deleteBuffer(f),f.name=0,mb[e]=null)}},p:function(a,b){for(var c=0;c<a;++c){var e=G[b+4*c>>2],f=nb[e];f&&(Z.deleteFramebuffer(f),
f.name=0,nb[e]=null)}},F:function(a){if(a){var b=R[a];b?(Z.deleteProgram(b),b.name=0,R[a]=null,W[a]=null):X(1281)}},H:function(a,b){for(var c=0;c<a;c++){var e=G[b+4*c>>2],f=S[e];f&&(Z.deleteRenderbuffer(f),f.name=0,S[e]=null)}},k:function(a){if(a){var b=V[a];b?(Z.deleteShader(b),V[a]=null):X(1281)}},Ca:function(a,b){for(var c=0;c<a;c++){var e=G[b+4*c>>2],f=T[e];f&&(Z.deleteTexture(f),f.name=0,T[e]=null)}},o:function(a){Z.depthFunc(a)},n:function(a){Z.depthMask(!!a)},a:function(a){Z.disable(a)},E:function(a){Z.disableVertexAttribArray(a)},
Wa:function(a,b,c){Z.drawArrays(a,b,c)},Xa:function(a,b,c,e){Z.drawElements(a,b,c,e)},c:function(a){Z.enable(a)},Ya:function(a){Z.enableVertexAttribArray(a)},i:function(a,b,c,e){Z.framebufferRenderbuffer(a,b,c,S[e])},j:function(a,b,c,e,f){Z.framebufferTexture2D(a,b,c,T[e],f)},z:function(a){Z.frontFace(a)},xa:function(a,b){ub(a,b,"createBuffer",mb)},s:function(a,b){ub(a,b,"createFramebuffer",nb)},ua:function(a,b){ub(a,b,"createRenderbuffer",S)},ra:function(a,b){ub(a,b,"createTexture",T)},ea:function(a,
b){return Z.getAttribLocation(R[a],F(b))},b:function(a,b){vb(a,b)},la:function(a,b,c,e){a=Z.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&e?D(a,E,e,b):0;c&&(G[c>>2]=b)},v:function(a,b,c){if(c)if(a>=lb)X(1281);else{var e=W[a];if(e)if(35716==b)a=Z.getProgramInfoLog(R[a]),null===a&&(a="(unknown error)"),G[c>>2]=a.length+1;else if(35719==b)G[c>>2]=e.$b;else if(35722==b){if(-1==e.Ub){a=R[a];var f=Z.getProgramParameter(a,35721);for(b=e.Ub=0;b<f;++b)e.Ub=Math.max(e.Ub,Z.getActiveAttrib(a,
b).name.length+1)}G[c>>2]=e.Ub}else if(35381==b){if(-1==e.Vb)for(a=R[a],f=Z.getProgramParameter(a,35382),b=e.Vb=0;b<f;++b)e.Vb=Math.max(e.Vb,Z.getActiveUniformBlockName(a,b).length+1);G[c>>2]=e.Vb}else G[c>>2]=Z.getProgramParameter(R[a],b);else X(1282)}else X(1281)},fa:function(a,b,c,e){a=Z.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&e?D(a,E,e,b):0;c&&(G[c>>2]=b)},t:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),G[c>>2]=a?a.length+1:0):35720==
b?(a=Z.getShaderSource(V[a]),G[c>>2]=a?a.length+1:0):G[c>>2]=Z.getShaderParameter(V[a],b):X(1281)},Ea:function(a){if(pb[a])return pb[a];switch(a){case 7939:var b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(e){return"GL_"+e}));b=wb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||X(1280);b=wb(b);break;case 7938:b=wb("OpenGL ES 2.0 ("+Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=wb(b);break;default:return X(1280),0}return pb[a]=b},u:function(a,b){b=F(b);var c=0;if("]"==b[b.length-1]){var e=b.lastIndexOf("[");c="]"!=b[e+1]?parseInt(b.slice(e+1)):0;b=b.slice(0,e)}return(a=W[a]&&W[a].lc[b])&&0<=c&&c<a[0]?a[1]+c:-1},ma:function(a){Z.linkProgram(R[a]);var b=R[a];a=W[a]={lc:{},$b:0,Ub:-1,Vb:-1};for(var c=a.lc,e=Z.getProgramParameter(b,35718),f=0;f<e;++f){var k=Z.getActiveUniform(b,f),g=k.name;a.$b=
Math.max(a.$b,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var n=Z.getUniformLocation(b,g);if(n){var m=Y(U);c[g]=[k.size,m];U[m]=n;for(var p=1;p<k.size;++p)n=Z.getUniformLocation(b,g+"["+p+"]"),m=Y(U),U[m]=n}}},A:function(a,b){Z.polygonOffset(a,b)},sa:function(a,b,c,e){Z.renderbufferStorage(a,b,c,e)},da:function(a,b,c,e){Z.scissor(a,b,c,e)},ia:function(a,b,c,e){for(var f="",k=0;k<b;++k){var g=e?G[e+4*k>>2]:-1;f+=F(G[c+4*k>>2],0>g?void 0:g)}Z.shaderSource(V[a],f)},Aa:function(a,
b,c){Z.stencilFunc(a,b,c)},$a:function(a,b,c,e){Z.stencilFuncSeparate(a,b,c,e)},m:function(a){Z.stencilMask(a)},za:function(a,b,c){Z.stencilOp(a,b,c)},_a:function(a,b,c,e){Z.stencilOpSeparate(a,b,c,e)},pa:function(a,b,c,e,f,k,g,n,m){Z.texImage2D(a,b,c,e,f,k,g,n,m?xb(n,g,e,f,m):null)},d:function(a,b,c){Z.texParameteri(a,b,c)},ka:function(a,b){Z.uniform1i(U[a],b)},h:function(a){Z.useProgram(R[a])},Va:function(a,b){Z.vertexAttribDivisor(a,b)},Za:function(a,b,c,e,f,k){Z.vertexAttribPointer(a,b,c,!!e,
f,k)},q:function(a,b,c,e){Z.viewport(a,b,c,e)},Oa:function(){d.ec=function(a){0!=zb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",d.ec)},Na:function(){d.kc=function(a){a=a.clipboardData.getData("text");la("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",d.kc)},Ma:function(a){d.Cc=[];a=F(a);a=document.getElementById(a);d.fc=function(b){b.stopPropagation();b.preventDefault()};d.hc=function(b){b.stopPropagation();b.preventDefault()};d.ic=function(b){b.stopPropagation();
b.preventDefault()};d.jc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;d.Dc=c;Ab(c.length);var e;for(e=0;e<c.length;e++)la("_sapp_emsc_drop",["number","string"],[e,c[e].name]);Bb(b.clientX,b.clientY)};a.addEventListener("dragenter",d.fc,!1);a.addEventListener("dragleave",d.hc,!1);a.addEventListener("dragover",d.ic,!1);a.addEventListener("drop",d.jc,!1)},Ka:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize=
"none";a.addEventListener("focusout",function(){Cb()});document.body.append(a)},Ja:function(){document.getElementById("_sokol_app_input_element").focus()},db:function(a){a=F(a);d.Wb=document.getElementById(a);d.Wb||console.log("sokol_app.h: invalid target:"+a);d.Wb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ha:function(){window.removeEventListener("beforeunload",d.ec)},Ga:function(){window.removeEventListener("paste",d.kc)},Fa:function(a){a=F(a);
a=document.getElementById(a);a.removeEventListener("dragenter",d.fc);a.removeEventListener("dragleave",d.hc);a.removeEventListener("dragover",d.ic);a.removeEventListener("drop",d.jc)},La:function(){d.Wb&&d.Wb.requestPointerLock&&d.Wb.requestPointerLock()},Ia:function(){document.getElementById("_sokol_app_input_element").blur()},na:function(){return d.Rb?d.Rb.bufferSize:0},ya:function(a,b,c){d.Ob=null;d.Rb=null;"undefined"!==typeof AudioContext?d.Ob=new AudioContext({sampleRate:a,latencyHint:"interactive"}):
"undefined"!==typeof webkitAudioContext?d.Ob=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(d.Ob=null,console.log("sokol_audio.h: no WebAudio support"));return d.Ob?(console.log("sokol_audio.h: sample rate ",d.Ob.sampleRate),d.Rb=d.Ob.createScriptProcessor(c,0,b),d.Rb.onaudioprocess=function(e){var f=e.outputBuffer.length,k=Db(f);if(k)for(var g=e.outputBuffer.numberOfChannels,n=0;n<g;n++)for(var m=e.outputBuffer.getChannelData(n),p=0;p<f;p++)m[p]=va[(k>>2)+(g*p+n)]},d.Rb.connect(d.Ob.destination),
a=function(){d.Ob&&"suspended"===d.Ob.state&&d.Ob.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},va:function(){return d.Ob?d.Ob.sampleRate:0},ga:function(){null!==d.Ob&&(d.Rb&&d.Rb.disconnect(),d.Ob.close(),d.Ob=null,d.Rb=null)},aa:function(){return performance.now()}};
(function(){function a(f){d.asm=f.exports;ia=d.asm.eb;f=ia.buffer;d.HEAP8=ma=new Int8Array(f);d.HEAP16=sa=new Int16Array(f);d.HEAP32=G=new Int32Array(f);d.HEAPU8=E=new Uint8Array(f);d.HEAPU16=ta=new Uint16Array(f);d.HEAPU32=ua=new Uint32Array(f);d.HEAPF32=va=new Float32Array(f);d.HEAPF64=H=new Float64Array(f);I=d.asm.fb;J--;d.monitorRunDependencies&&d.monitorRunDependencies(J);0==J&&(null!==Ca&&(clearInterval(Ca),Ca=null),K&&(f=K,K=null,f()))}function b(f){a(f.instance)}function c(f){return Ha().then(function(k){return WebAssembly.instantiate(k,
e)}).then(f,function(k){A("failed to asynchronously prepare wasm: "+k);z(k)})}var e={a:Eb};J++;d.monitorRunDependencies&&d.monitorRunDependencies(J);if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return A("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return B||"function"!==typeof WebAssembly.instantiateStreaming||Ea()||Da("file://")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
e).then(b,function(k){A("wasm streaming compile failed: "+k);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var yb=d.___wasm_call_ctors=function(){return(yb=d.___wasm_call_ctors=d.asm.gb).apply(null,arguments)},Cb=d.__sapp_emsc_notify_keyboard_hidden=function(){return(Cb=d.__sapp_emsc_notify_keyboard_hidden=d.asm.hb).apply(null,arguments)};d.__sapp_emsc_onpaste=function(){return(d.__sapp_emsc_onpaste=d.asm.ib).apply(null,arguments)};
var zb=d.__sapp_html5_get_ask_leave_site=function(){return(zb=d.__sapp_html5_get_ask_leave_site=d.asm.jb).apply(null,arguments)},Ab=d.__sapp_emsc_begin_drop=function(){return(Ab=d.__sapp_emsc_begin_drop=d.asm.kb).apply(null,arguments)};d.__sapp_emsc_drop=function(){return(d.__sapp_emsc_drop=d.asm.lb).apply(null,arguments)};var Bb=d.__sapp_emsc_end_drop=function(){return(Bb=d.__sapp_emsc_end_drop=d.asm.mb).apply(null,arguments)};
d.__sapp_emsc_invoke_fetch_cb=function(){return(d.__sapp_emsc_invoke_fetch_cb=d.asm.nb).apply(null,arguments)};d.___em_js__sapp_js_create_textfield=function(){return(d.___em_js__sapp_js_create_textfield=d.asm.ob).apply(null,arguments)};d.___em_js__sapp_js_focus_textfield=function(){return(d.___em_js__sapp_js_focus_textfield=d.asm.pb).apply(null,arguments)};d.___em_js__sapp_js_unfocus_textfield=function(){return(d.___em_js__sapp_js_unfocus_textfield=d.asm.qb).apply(null,arguments)};
d.___em_js__sapp_js_add_beforeunload_listener=function(){return(d.___em_js__sapp_js_add_beforeunload_listener=d.asm.rb).apply(null,arguments)};d.___em_js__sapp_js_remove_beforeunload_listener=function(){return(d.___em_js__sapp_js_remove_beforeunload_listener=d.asm.sb).apply(null,arguments)};d.___em_js__sapp_js_add_clipboard_listener=function(){return(d.___em_js__sapp_js_add_clipboard_listener=d.asm.tb).apply(null,arguments)};
d.___em_js__sapp_js_remove_clipboard_listener=function(){return(d.___em_js__sapp_js_remove_clipboard_listener=d.asm.ub).apply(null,arguments)};d.___em_js__sapp_js_write_clipboard=function(){return(d.___em_js__sapp_js_write_clipboard=d.asm.vb).apply(null,arguments)};d.___em_js__sapp_js_add_dragndrop_listeners=function(){return(d.___em_js__sapp_js_add_dragndrop_listeners=d.asm.wb).apply(null,arguments)};
d.___em_js__sapp_js_dropped_file_size=function(){return(d.___em_js__sapp_js_dropped_file_size=d.asm.xb).apply(null,arguments)};d.___em_js__sapp_js_fetch_dropped_file=function(){return(d.___em_js__sapp_js_fetch_dropped_file=d.asm.yb).apply(null,arguments)};d.___em_js__sapp_js_remove_dragndrop_listeners=function(){return(d.___em_js__sapp_js_remove_dragndrop_listeners=d.asm.zb).apply(null,arguments)};
d.___em_js__sapp_js_pointer_init=function(){return(d.___em_js__sapp_js_pointer_init=d.asm.Ab).apply(null,arguments)};d.___em_js__sapp_js_request_pointerlock=function(){return(d.___em_js__sapp_js_request_pointerlock=d.asm.Bb).apply(null,arguments)};d.___em_js__sapp_js_exit_pointerlock=function(){return(d.___em_js__sapp_js_exit_pointerlock=d.asm.Cb).apply(null,arguments)};d._main=function(){return(d._main=d.asm.Db).apply(null,arguments)};
var P=d._malloc=function(){return(P=d._malloc=d.asm.Eb).apply(null,arguments)},Db=d.__saudio_emsc_pull=function(){return(Db=d.__saudio_emsc_pull=d.asm.Fb).apply(null,arguments)};d.___em_js__saudio_js_init=function(){return(d.___em_js__saudio_js_init=d.asm.Gb).apply(null,arguments)};d.___em_js__saudio_js_shutdown=function(){return(d.___em_js__saudio_js_shutdown=d.asm.Hb).apply(null,arguments)};
d.___em_js__saudio_js_sample_rate=function(){return(d.___em_js__saudio_js_sample_rate=d.asm.Ib).apply(null,arguments)};d.___em_js__saudio_js_buffer_frames=function(){return(d.___em_js__saudio_js_buffer_frames=d.asm.Jb).apply(null,arguments)};d.___em_js__stm_js_perfnow=function(){return(d.___em_js__stm_js_perfnow=d.asm.Kb).apply(null,arguments)};
var na=d.stackSave=function(){return(na=d.stackSave=d.asm.Lb).apply(null,arguments)},oa=d.stackRestore=function(){return(oa=d.stackRestore=d.asm.Mb).apply(null,arguments)},C=d.stackAlloc=function(){return(C=d.stackAlloc=d.asm.Nb).apply(null,arguments)},Fb;function ha(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Gb(){Fb||Hb();Fb||(K=Gb)};
function Hb(a){function b(){if(!Fb&&(Fb=!0,d.calledRun=!0,!ja)){Ia(xa);Ia(ya);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Ib){var c=a,e=d._main;c=c||[];var f=c.length+1,k=C(4*(f+1));G[k>>2]=ra(aa);for(var g=1;g<f;g++)G[(k>>2)+g]=ra(c[g-1]);G[(k>>2)+f]=0;try{var n=e(f,k);if(!noExitRuntime||0!==n){if(!noExitRuntime){if(d.onExit)d.onExit(n);ja=!0}t(n,new ha(n))}}catch(m){m instanceof ha||("unwind"==m?noExitRuntime=!0:((c=m)&&"object"===typeof m&&m.stack&&(c=[m,m.stack]),A("exception thrown: "+
c),t(1,m)))}finally{}}if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)c=d.postRun.shift(),Aa.unshift(c);Ia(Aa)}}a=a||r;if(!(0<J)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ba();Ia(wa);0<J||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b())}}d.run=Hb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();
var Ib=!0;d.noInitialRun&&(Ib=!1);noExitRuntime=!0;Hb();
